# convert_to_c_array.py
import os

def tflite_to_header(tflite_path, header_path):
    # 读取 .tflite 二进制文件
    with open(tflite_path, 'rb') as f:
        data = f.read()
    
    # 获取文件名（不含扩展名）作为数组名
    filename = os.path.basename(tflite_path).replace('.', '_')
    
    # 生成 C 头文件内容
    with open(header_path, 'w') as f:
        f.write(f"// Auto-generated by convert_to_c_array.py\n")
        f.write(f"#ifndef {filename.upper()}_H_\n")
        f.write(f"#define {filename.upper()}_H_\n\n")
        
        # 写入数组长度
        f.write(f"const unsigned int {filename}_len = {len(data)};\n\n")
        
        # 写入数组数据
        f.write(f"const unsigned char {filename}[] = {{\n")
        for i, byte in enumerate(data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x}, ")
            if (i + 1) % 12 == 0:
                f.write("\n")
        if len(data) % 12 != 0:
            f.write("\n")
        f.write(f"}};\n\n")
        
        f.write(f"#endif  // {filename.upper()}_H_\n")

if __name__ == "__main__":
    # 输入：model_quantized.tflite
    # 输出：model_data.h
    tflite_to_header("model_quantized.tflite", "model_data.h")
    print("Successfully generated model_data.h")